#[profile.nvidia-259]
# Max number of virtual displays. Usually 1 if you want a simple remote gaming VM
#num_displays = 1
# Maximum display width in the VM
#display_width = 1920
# Maximum display height in the VM
#display_height = 1080
# This is the product of display_width and display_height so 1920 * 1080 = 2073600
#max_pixels = 2073600
# Enables CUDA support. Either 1 or 0 for enabled/disabled
#cuda_enabled = 1
# This controls the frame rate limiter, if you enable it your fps in the VM get locked to 60fps. Either 1 or 0 for enabled/disabled
#frl_enabled = 1
# In combination with the framebuffer size
# above, these two lines will give you a VM
# with 2GB of VRAM (framebuffer + framebuffer_reservation = VRAM size in bytes).
# See below for some other sizes
#framebuffer = 0x74000000
#framebuffer_reservation = 0xC000000
