name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build dev & Test
      run: |
        cargo build --verbose
        cargo test --verbose
        
    - name: Build release
      run: cargo build --release
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: lib_release
        path: target/release/*.so
